### ISSUE TITLE
Not Teensy. If you call it Teensycnc then use a Teensy, not a PIC

### ISSUE THREAD

**Issue by whitetd** [seishuku/TeensyCNC#1]
Not Teensy. If you call it Teensycnc then use a Teensy, not a PIC

**Comment by seishuku** [comment]
?
I am using a Teensy.

The original MCU on the Cricut Mini used PIC, I'm just referencing the pins after the PIC was removed from the board and jumpers soldered in, to go to the Teensy.

**Comment by whitetd** [comment]
Oh, ok Sorry, all I could see referanced the pic.
