### ISSUE TITLE
Teensy 4.0 hex File

### ISSUE THREAD

**Issue by CalebZim** [seishuku/TeensyCNC#2]
Can you make another branch that works with the Teensy 4.0. The main.hex cannot load. It  would be very much appreciated.
Thanks

**Comment by seishuku** [comment]
With out having a Teensy 4 on hand, I probably couldn't make one that "just
works"... It's a completely different SOC than any of the previous Teensys.

I do plan on getting a Teensy 4 at some point, since it's a really nice
powerful MCU board, but that probably won't happen for a while.

**Comment by CalebZim** [comment]
Ok, so even if I build the files for the 4, it would not work?

**Comment by seishuku** [comment]
No, most of the MCU code definitions (addresses for modules, ports, etc)
are all likely different (iMX MCU is quite different than the Kinetis MCU).

If I get some time, I could try porting the code over to the iMX chip, but
even if I can get it to compile, I doubt it would run as is... At the very
least it wouldn't likely run correctly.

**Comment by CalebZim** [comment]
Will any version of a teensy 3 work? What exact version did you use?

**Comment by seishuku** [comment]
3.1/3.2 will work for sure, I *think* a 3.0 will work too, though there are
some differences between a 3.0 and 3.1/3.2 that may break some things. I'm
80% sure a 3.0 will work. lol

A 3.5/3.6 would need some minor changes, I do have a 3.6 and have been
meaning to make a branch for that.

I used a 3.2.

**Comment by CalebZim** [comment]
OK, I will try a 3.2.
Thanks for answering all my questions.
